name: cached_video_preview
description: Flutter plugin that can help you get remote or local video preview image and cache it.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.6+1

environment:
  sdk: ">=2.14.4 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  metadata_fetch:
    git: https://github.com/mahdiar-om/metadata_fetch
  video_thumbnail: ^0.5.0
  moor: ^4.4.1
  moor_flutter: ^4.0.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.2
  path: ^1.8.0
  platform: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^4.4.1
  build_runner: ^2.1.1
  lints: ^2.1.1
